# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "a782cde34d86e47c90af6eaf7d48f88c"
name = "POS QR Extension"
handle = "pos-qr-extension-1"
application_url = "https://unemployment-arizona-granted-rick.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_orders"

[auth]
redirect_urls = ["https://unemployment-arizona-granted-rick.trycloudflare.com/auth/callback", "https://unemployment-arizona-granted-rick.trycloudflare.com/auth/shopify/callback", "https://unemployment-arizona-granted-rick.trycloudflare.com/api/auth/callback"]

[pos]
embedded = false
