# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "7f15d7d86c6b2e8fe41881ce07a58142"
name = "pos-qr-extension"
handle = "pos-qr-extension-2"
application_url = "https://verified-textiles-blowing-examples.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2025-07"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,read_orders,write_orders,write_products"

[auth]
redirect_urls = ["https://verified-textiles-blowing-examples.trycloudflare.com/auth/callback", "https://verified-textiles-blowing-examples.trycloudflare.com/auth/shopify/callback", "https://verified-textiles-blowing-examples.trycloudflare.com/api/auth/callback"]

[pos]
embedded = false
