# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "1943dc051783405c5ec37146f07d485c"
name = "pos-qr-extension-only"
handle = "pos-qr-extension-only-1"
application_url = "https://fool-tvs-medication-statistics.trycloudflare.com"
embedded = true

[webhooks]
api_version = "2025-07"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_orders,read_products"

[auth]
redirect_urls = ["https://fool-tvs-medication-statistics.trycloudflare.com/auth/callback", "https://fool-tvs-medication-statistics.trycloudflare.com/auth/shopify/callback", "https://fool-tvs-medication-statistics.trycloudflare.com/api/auth/callback"]

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
